name: Genera PDF CorsoWCAG

on:
  push:
    branches: [ main ]
    paths:
      - 'slide/*.*'
      - '.github/workflows/generatepdf.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Generate pdf
      run: |
        cd slide
        cp 'CorsoWCAG.md' 'CorsoWCAG-backup.md'
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" 'CorsoWCAG.md'
        sed -i "s/%time%/$(date +'%H:%M')/g" 'CorsoWCAG.md'
        npx @marp-team/marp-cli@latest 'CorsoWCAG.md' --pdf --allow-local-files --pdf-outlines --pdf-outlines.pages=false
        rm 'CorsoWCAG.md'
        mv 'CorsoWCAG-backup.md' 'CorsoWCAG.md'

    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slides"
        git push

